### ISSUE TITLE
Should you rename 'log' button to 'ln'?

### ISSUE THREAD

**Issue by DanielLyi** [HouariZegai/Calculator#10]
I think it would be better to call the natural logarithm button as 'ln' to remove any possible confusions.

**Comment by AbhishekAnand01** [comment]
I am  also agree with your comment.

We can change the log button caption to ln  by editing the below code.

![image](https://user-images.githubusercontent.com/39114448/93865209-0526a700-fc94-11ea-8cd4-d23501f0e1cb.png)

**Comment by xdvrx1** [comment]
yup, but for me, `LN` is much better rather than `ln`, at first look letter `l` might be confused with big i `I`, isn't it?

**Comment by HouariZegai** [comment]
Resolved on PR #11
