### ISSUE TITLE
Patrones de diseño

### ISSUE THREAD

**Issue by ajvilleg10** [HouariZegai/Calculator#30]
Muy buenas noches soy un estudiante de Ingeniería en Computación y me ha tocado hacer un deber de Diseño de Software en el que debo buscar repositorios y ver fallos que se puedan solucionar con algún patrón de diseño. En este caso te recomiendo que apliques el patrón Composite para mantener una estructura sobre las partes de la factura y así poder manejar la organización de los datos que esta conlleva a su vez, que se maneja los cálculos de dicha factura de forma ordenada. Espero que mi recomendación te sirva de mucho.

**Comment by HouariZegai** [comment]
Hello,
Can you explain what you are talking about in English?
